builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: ./cmd/go-congen
brews:
  - tap:
      owner: reddec
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage:  https://github.com/reddec/go-congen
    description: Generates Go controller based on HTML
    license: MIT
    test: |
      system "#{bin}/go-congen --help"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "go-congen"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
