# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCongen < Formula
  desc "Generates Go controller based on HTML"
  homepage "https://github.com/reddec/go-congen"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.1/go-congen_0.0.1_darwin_amd64.tar.gz"
      sha256 "a9e88f92f41827afe7a5d8895b7834db54f95a92b0eb33be1d854b5df50ad0f0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.1/go-congen_0.0.1_darwin_arm64.tar.gz"
      sha256 "06d3750f63d7958ef93281c4c8f187f74b650b7e92c2e282cbaef3b28645bc6f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.1/go-congen_0.0.1_linux_amd64.tar.gz"
      sha256 "a1d2db1be8ea325b2f73ce6534bef8e0a4215242741757865b06cd70edc78666"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.1/go-congen_0.0.1_linux_armv6.tar.gz"
      sha256 "d86b2f81ef4cfd61b017f3b30b900dbb83e1c8354b58e9f493bd828ed137b0f8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.1/go-congen_0.0.1_linux_arm64.tar.gz"
      sha256 "ed3ddd3011c1e9bcb2af763181ee31a8fc5d9fffd8e04fc0736aeeff3e8080da"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "go-congen"
  end

  test do
    system "#{bin}/go-congen --help"
  end
end
